- job:
    name: designate-bind9-stable-2024-1
    parent: designate-bind9
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.1

- job:
    name: designate-bind9-stable-2024-2
    parent: designate-bind9
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.2

- job:
    name: designate-bind9-stable-2023-2
    parent: designate-bind9
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2023.2

- job:
    name: designate-bind9-stable-2023-1
    parent: designate-bind9
    nodeset: openstack-single-node-focal
    override-checkout: stable/2023.1

- project:
    templates:
      - designate-devstack-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - tempest-plugin-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - designate-bind9-stable-2024-2
        - designate-bind9-stable-2024-1
        - designate-bind9-stable-2023-2
        - designate-bind9-stable-2023-1
        - neutron-tempest-plugin-designate-scenario
