- job:
    name: designate-bind9-stable-2024-1
    parent: designate-bind9
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.1

- job:
    name: designate-bind9-stable-2024-2
    parent: designate-bind9
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.2

- job:
    name: designate-bind9-stable-2023-2
    parent: designate-bind9
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2023.2

- job:
    name: designate-multipool
    parent: designate-base
    nodeset: openstack-single-node-jammy
    vars:
      devstack_local_conf:
        test-config:
          "$TEMPEST_CONFIG":
            dns_feature_enabled:
              test_multipool_with_delete_opt: True
      tempest_test_regex: ^designate_tempest_plugin.tests.scenario.v2.test_designate_multipool

- project:
    templates:
      - designate-devstack-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - tempest-plugin-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - designate-bind9-stable-2024-2
        - designate-bind9-stable-2024-1
        - designate-bind9-stable-2023-2
        - designate-multipool
        - neutron-tempest-plugin-designate-scenario
