- job:
    name: designate-bind9-stable-antelope
    parent: designate-bind9
    nodeset: openstack-single-node-focal
    override-checkout: stable/2023.1

- job:
    name: designate-bind9-stable-zed
    parent: designate-bind9
    nodeset: openstack-single-node-focal
    override-checkout: stable/zed

- job:
    name: designate-bind9-stable-yoga
    parent: designate-bind9
    nodeset: openstack-single-node-focal
    override-checkout: stable/yoga

- project:
    templates:
      - designate-devstack-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - tempest-plugin-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - designate-bind9-stable-antelope
        - designate-bind9-stable-zed
        - designate-bind9-stable-yoga
        - neutron-tempest-plugin-designate-scenario
