- project:
    templates:
      - designate-devstack-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - tempest-plugin-jobs
    check:
      jobs:
        - neutron-tempest-plugin-designate-scenario
    gate:
      queue: designate
