- name: Ensure target directory exists
  file:
    path: "{{ stage_dir }}/etc/bind"
    state: directory

- name: Find bind config files
  find:
    path: /etc/bind
    file_type: any
  register: bind_configs

- name: Copy bind configurations
  copy:
    src: "{{ item.path }}"
    dest: "{{ stage_dir }}/etc/bind/{{ item.path | basename }}"
    remote_src: true
  with_items: "{{ bind_configs.files }}"
  when: item.isreg or item.islnk

# NOTE(frickler) Copied from devstack role export-devstack-journal
- name: Ensure {{ stage_dir }}/logs exists
  become: true
  file:
    path: "{{ stage_dir }}/logs"
    state: directory
    owner: "{{ ansible_user }}"

- name: Collect bind journal
  become: true
  shell:
    cmd: |
      journalctl -o short-precise --unit named > {{ stage_dir }}/logs/bind9.txt
